### [인증] 회원 정보를 조회
GET {{host_api}}/api/v1/user/me
Authorization: Bearer {{ACCESS_TOKEN}}

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### [인증] 회원 정보를 수정
PUT {{host_api}}/api/v1/user/me
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "name": "will",
    "profileUrl": "https://image.com"
}
