create table "member"
(
    "id"              int8 generated by default as identity,
    "social_id"       varchar(200) not null,
    "social_provider" varchar(30)  not null,
    "name"            varchar(30)  not null,
    "profile_url"     varchar(2048),
    "refresh_token"   varchar(255),
    "created_at"      timestamp,
    "updated_at"      timestamp,
    primary key ("id")
);


CREATE UNIQUE INDEX "uni_member_1"
    ON member ("social_id", "social_provider");

CREATE INDEX "idx_member_1"
    ON member ("refresh_token");



create table "exercise_category"
(
    "id"           int8 generated by default as identity,
    "parent_id"    int8,
    "depth"        int4         not null,
    "english_name" varchar(255) not null,
    "korean_name"  varchar(255) not null,
    "created_at"   timestamp,
    "updated_at"   timestamp,
    primary key ("id")
);


CREATE INDEX "idx_exercise_category_1"
    ON exercise_category ("parent_id");



create table "poster"
(
    "id"               int8 generated by default as identity,
    "emotion"          varchar(255) not null,
    "image_url"        varchar(255) not null,
    "origin_image_url" varchar(255) not null,
    "poster_status"    varchar(255) not null,
    "user_id"          int8         not null,
    "created_at"       timestamp,
    "updated_at"       timestamp,
    primary key ("id")
)

CREATE INDEX "idx_poster_1"
    ON poster ("user_id");



create table "poster_exercise_category"
(
    "id"                   int8 generated by default as identity,
    "exercise_category_id" int8,
    "poster_id"            int8,
    "created_at"           timestamp,
    "updated_at"           timestamp,
    primary key ("id")
)
