create table "member"
(
    "id"              int8 generated by default as identity,
    "social_id"       varchar(200) not null,
    "social_provider" varchar(30)  not null,
    "name"            varchar(30)  not null,
    "profile_url"     varchar(2048) default null,
    "refresh_token"   varchar(255)  default null,
    "created_at"      timestamp     default null,
    "updated_at"      timestamp     default null,
    primary key ("id")
);


CREATE UNIQUE INDEX "uni_member_1"
    ON member ("social_id", "social_provider");

CREATE INDEX "idx_member_1"
    ON member ("refresh_token");


create table "exercise_category"
(
    "id"           int8 generated by default as identity,
    "parent_id"    int8      default null,
    "depth"        int4        not null,
    "english_name" varchar(50) not null,
    "korean_name"  varchar(50) not null,
    "created_at"   timestamp default null,
    "updated_at"   timestamp default null,
    primary key ("id")
);


CREATE INDEX "idx_exercise_category_1"
    ON exercise_category ("parent_id");



create table "poster"
(
    "id"               int8 generated by default as identity,
    "user_id"          int8         not null,
    "image_url"        varchar(255) not null,
    "origin_image_url" varchar(255) not null,
    "emotion"          varchar(30)  not null,
    "poster_status"    varchar(30)  not null,
    "created_at"       timestamp default null,
    "updated_at"       timestamp default null,
    primary key ("id")
);

CREATE INDEX "idx_poster_1"
    ON poster ("user_id", poster_status);



create table "poster_exercise_category"
(
    "id"                   int8 generated by default as identity,
    "poster_id"            int8 not null,
    "exercise_category_id" int8 not null,
    "created_at"           timestamp default null,
    "updated_at"           timestamp default null,
    primary key ("id")
);


CREATE INDEX "idx_poster_exercise_category_1"
    ON poster_exercise_category ("poster_id");


CREATE INDEX "idx_poster_exercise_category_2"
    ON poster_exercise_category ("exercise_category_id");
